/**
 * Parses a command line string into an array of arguments, preserving quoted strings.
 *
 * This function handles:
 * - Space-separated arguments
 * - Double-quoted strings (preserves spaces within)
 * - Single-quoted strings (preserves spaces within)
 *
 * @param argsString The command line string to parse
 * @returns An array of parsed arguments
 */
export function parseCommandLineArgs(argsString: string): string[] {
  if (!argsString) return [];

  const result: string[] = [];
  let current = '';
  let inDoubleQuote = false;
  let inSingleQuote = false;

  for (let i = 0; i < argsString.length; i++) {
    const char = argsString[i];

    // Handle quotes
    if (char === '"' && !inSingleQuote) {
      inDoubleQuote = !inDoubleQuote;
      continue;
    }

    if (char === "'" && !inDoubleQuote) {
      inSingleQuote = !inSingleQuote;
      continue;
    }

    // Handle spaces (only split on spaces outside of quotes)
    if (char === ' ' && !inDoubleQuote && !inSingleQuote) {
      if (current) {
        result.push(current);
        current = '';
      }
      continue;
    }

    // Add character to current argument
    current += char;
  }

  // Add the last argument if there is one
  if (current) {
    result.push(current);
  }

  return result;
}

/**
 * Removes HTML-style comments from a string.
 *
 * @param markdownContent The string containing markdown content
 * @returns The string with HTML comments removed
 */
export function stripHtmlComments(markdownContent: string): string {
  return markdownContent.replace(/<!--[\s\S]*?-->/g, '');
}

/**
 * Processes PR body content to omit large code blocks.
 * This is especially useful when targeting PRs generated by gen-pr which may contain large code blocks.
 *
 * @param body The PR body content
 * @returns The processed body with large code blocks truncated
 */
export function omitLargeCodeBlocks(body: string): string {
  if (!body) return '';

  const MAX_CODE_BLOCK_SIZE = 500; // Maximum characters for a single code block
  const CODE_BLOCK_REGEX = /```[\s\S]*?```/g;

  return body.replace(CODE_BLOCK_REGEX, (match) => {
    if (match.length <= MAX_CODE_BLOCK_SIZE) {
      return match;
    }

    // Extract the language identifier if present
    const lines = match.split('\n');
    const firstLine = lines[0];
    const lastLine = lines[lines.length - 1];

    // Keep first few lines and add truncation message
    const preview = lines.slice(0, 5).join('\n');

    return `${firstLine}\n${preview.substring(firstLine.length + 1)}\n... (large code block truncated - ${match.length} characters) ...\n${lastLine}`;
  });
}
